2023/10/07 20:53:26 [error] 29#29: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "POST /retrocrypto_api/traditional HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/traditional", host: "localhost", referrer: "https://localhost/retrocrypto"
2023/10/07 20:53:59 [error] 29#29: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /retrocrypto_api/ HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/", host: "localhost"
2023/10/07 21:07:43 [error] 29#29: *89 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /retrocrypto_api/ HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/", host: "localhost"
2023/10/07 21:07:46 [error] 29#29: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "POST /retrocrypto_api/traditional HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/traditional", host: "localhost", referrer: "https://localhost/retrocrypto"
2023/10/07 21:07:50 [error] 29#29: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "POST /retrocrypto_api/traditional HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/traditional", host: "localhost", referrer: "https://localhost/retrocrypto"
2023/10/07 21:07:53 [error] 29#29: *110 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 21:08:09 [error] 29#29: *110 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 22:45:18 [error] 22#22: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 22:52:34 [error] 22#22: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 22:52:55 [error] 22#22: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "POST /retrocrypto_api/traditional HTTP/1.1", upstream: "http://193.168.1.30:80/retrocrypto_api/traditional", host: "localhost", referrer: "https://localhost/retrocrypto"
2023/10/07 22:53:22 [error] 22#22: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 22:53:30 [error] 22#22: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost"
2023/10/07 23:15:51 [error] 22#22: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 23:15:59 [error] 22#22: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost", referrer: "https://localhost/selftrack"
2023/10/07 23:16:09 [error] 22#22: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /selftrack_api/ HTTP/1.1", upstream: "http://193.168.1.40:80/selftrack_api/", host: "localhost"
2023/10/07 23:46:14 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /traditional/ HTTP/1.1", upstream: "http://193.168.1.30:80/traditional/", host: "localhost", referrer: "https://localhost/retrocrypto"
2023/10/07 23:46:54 [error] 29#29: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 193.168.1.1, server: localhost, request: "GET /exporter/ HTTP/1.1", upstream: "http://193.168.1.40:80/exporter/", host: "localhost", referrer: "https://localhost/selftrack"
